######################################################################
# Automatically generated by qmake (2.01a) Fri Jan 5 19:33:30 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += editor.h
SOURCES += editor.cpp main.cpp
