######################################################################
# Automatically generated by qmake (2.01a) Mon Jan 15 13:33:57 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . Library
INCLUDEPATH += . Library

# Input
HEADERS += editor.h Library/library.cpp editor.cpp
SOURCES += editor.cpp main.cpp Library/library.cpp
